apiVersion: v1
kind: Service
metadata:
  name: messenger-service
spec:
  selector:
    app: messenger
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - name: messenger
          image: vyacheslavshrot/messenger:latest
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "$(MONGO_INITDB_ROOT_USERNAME)"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "$(MONGO_INITDB_ROOT_PASSWORD)"
            - name: MONGO_DB_AUTH_SOURCE
              value: "$(MONGO_DB_AUTH_SOURCE)"
            - name: SECRET_KEY
              value: "$(SECRET_KEY)"
