name: CI/CD

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vyacheslavshrot
          password: Slavic2005Ss

      - name: Build Docker image
        run: docker build -t vyacheslavshrot/messenger:latest .

      - name: Push Docker image to Docker Hub
        run: docker push vyacheslavshrot/messenger:latest